name: CI
on:
  push:
  pull_request:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - uses: astral-sh/setup-uv@v3
      - name: Sync deps (main + dev)
        run: uv sync --group dev
      - name: Run pre-commit (ruff, mypy)
        run: uv run pre-commit run --all-files
      - name: Run tests (pytest)
        run: uv run pytest -q
